version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hasib
      MYSQL_DATABASE: hasib-db
      MYSQL_USER: user_hasib
      MYSQL_PASSWORD: hasib_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile  
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  db_data: {}