services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hasib
      MYSQL_DATABASE: hasib-db
      MYSQL_USER: user_hasib
      MYSQL_PASSWORD: hasib_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: