name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env file for Backend
        run: |
          cp backend/.env.example backend/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build  # Build images before starting services
          echo "Waiting for services to start..."
          sleep 15  # Allow some time for services to start

      - name: Check Backend Service
        run: |
          echo "Checking Backend Service..."
          curl -f http://localhost:8000 || exit 1

      - name: Check Frontend Service
        run: |
          echo "Checking Frontend Service..."
          curl -f http://localhost || exit 1

      - name: Tear Down
        if: always()  # Ensure this step runs even if previous steps fail
        run: |
          echo "Tearing down Docker Compose..."
          docker-compose down
